# === Bot Configuration ===
test_mode: true  # Set to false for live trading

# === Trading Parameters ===
trade_amount_usd: 5
slippage: 0.10
take_profit: 0.5
stop_loss: 0.25
use_dynamic_tp: false

# === Strategy Thresholds ===
min_momentum_pct: 0.0001  # Very low momentum requirement
min_volume_24h_for_buy: 1000
min_liquidity_usd_for_buy: 2000
min_price_usd: 0.0000001

# Fast-path thresholds for first-seen tokens
fastpath_min_volume_24h: 5000
fastpath_min_liquidity_usd: 10000
fastpath_min_sent_score: 5

# === Pre-buy Delisting Check ===
enable_pre_buy_delisting_check: false  # Temporarily disabled due to API issues
pre_buy_check_sensitivity: "lenient"
pre_buy_check_timeout: 10

# === Chain Support ===
supported_chains: ["ethereum", "solana", "base"]

# === Risk Management ===
max_concurrent_positions: 5
daily_loss_limit_usd: 50.0
max_losing_streak: 3
circuit_breaker_minutes: 60
per_trade_max_usd: 5
min_wallet_balance_buffer: 0.01

# === Smart Cleanup ===
enable_smart_blacklist_cleanup: true
blacklist_cleanup_interval: 1  # Every loop
blacklist_keep_failure_threshold: 3
enable_smart_delisted_cleanup: true
delisted_cleanup_interval: 1  # Every loop

# === API and External Services ===
# Temporarily disable problematic APIs
enable_sentiment_checks: false  # Disabled due to Twitter/Nitter issues
enable_tokensniffer: false  # Disabled temporarily
enable_price_verification: false  # Trust DexScreener data more

# === Jupiter API Settings ===
enable_jupiter_pre_check: false  # Allow tokens to proceed even if Jupiter pre-check fails
jupiter_pre_check_strict: false  # Don't reject tokens based on Jupiter pre-check alone

# === Raydium Fallback Settings ===
enable_raydium_fallback: true  # Enable Raydium fallback when Jupiter fails
raydium_slippage: 0.10  # 10% slippage for Raydium trades
raydium_timeout: 15  # Timeout for Raydium API calls
min_raydium_liquidity: 1000.0  # Minimum liquidity required for Raydium trades

# === Telegram ===
telegram_bot_token: ""
telegram_chat_id: ""

# === Gas Settings ===
gas_blocks: 1
gas_reward_percentile: 50
gas_basefee_headroom: 0.1
gas_priority_min_gwei: 1
gas_priority_max_gwei: 100
gas_ceiling_gwei: 200
gas_multiplier: 1.2
gas_extra_priority_gwei: 0

# === Uniswap Settings ===
use_supporting_fee_swap: true
requote_delay_seconds: 10
requote_slippage_buffer: 0.005

# === Monitoring ===
trailing_stop_percent: 0.1

# === Price Memory ===
price_memory_ttl_minutes: 15
price_memory_prune_hours: 24

# === Trusted Tokens ===
trusted_tokens: []

# === State Management ===
reset_state_now: false