# === Trade Execution ===
trade_amount_usd: 10              # Amount per trade in USD - Increased for better positions
slippage: 0.02                    # 2% max slippage
use_supporting_fee_swap: true     # Use fee-supporting swap function for taxed tokens
requote_delay_seconds: 10         # If build/send delay > this, re-quote before sending
requote_slippage_buffer: 0.005    # Extra slippage on re-quote (0.5%) to reduce false fails

# Profit & Risk Management
take_profit: 0.5                  # Base TP = 50%
use_dynamic_tp: true              # Enable dynamic TP logic
stop_loss: 0.25                   # Stop loss at 25%
trailing_stop_percent: 0.1        # 10% trailing stop
pump_guard_max_pct: 0.25          # 25% better than EMA = suspicious pump → block
price_impact_max_pct: 0.15        # 15% worse than EMA = adverse impact → block

# Position & Risk Controls
max_concurrent_positions: 5       # Max open positions at a time
daily_loss_limit_usd: 100         # Daily loss cap before circuit breaker - Increased for more opportunities
max_losing_streak: 3              # Consecutive losing trades before pause
circuit_breaker_minutes: 60       # Pause duration if circuit breaker triggered
per_trade_max_usd: 25             # Max USD per trade
min_wallet_balance_buffer: 0.01   # Keep 1% of balance for gas fees

# Liquidity / Size-Impact Sanity
max_size_price_impact_pct: 0.20   # Abort if size would move price >20% (approx: size/reserve)
min_pair_reserve_weth: 5.0        # Require ≥ 5 WETH on the pool’s WETH side

# === Strategy: Momentum-based Buy Logic ===
min_momentum_pct: 0.0002          # +0.02% change within TTL - Ideal balance for opportunities vs noise
min_volume_24h_for_buy: 2000      # Min 24h volume (USD) - Increased from 500 to 2000 for safety
min_liquidity_usd_for_buy: 5000   # Min liquidity (USD) - Increased from 1000 to 5000 for safety
min_price_usd: 0.0000001          # Ignore dust tokens
enable_pre_buy_delisting_check: true   # Re-enabled to prevent buying delisted tokens
pre_buy_check_sensitivity: "moderate"  # Options: "strict", "moderate", "lenient" - Controls how aggressive the delisting check is
pre_buy_check_timeout: 10         # Timeout in seconds for price verification APIs

# Fast-path thresholds for first-seen tokens
fastpath_min_volume_24h: 10000    # Min 24h volume (USD) - Increased from 2000 to 10000 for safety
fastpath_min_liquidity_usd: 25000 # Min liquidity (USD) - Increased from 5000 to 25000 for safety
fastpath_min_sent_score: 10       # OR mentions >= 1 - Even more reduced for more opportunities

# TP limits for dynamic TP logic
tp_min: 0.20                      # 20% min TP when dynamic
tp_max: 1.00                      # 100% max TP when dynamic

# === Housekeeping ===
price_memory_ttl_minutes: 15      # TTL for momentum checks
price_memory_prune_hours: 24      # Prune old EMA/quote entries
price_ema_alpha: 0.3              # EMA smoothing factor for price guards

# === Smart Blacklist Maintenance ===
enable_smart_blacklist_cleanup: true    # Auto-clean blacklist every 6 loops
blacklist_cleanup_interval: 6           # Clean every N loops (6 = every 6 hours)
blacklist_keep_failure_threshold: 3     # Keep tokens with N+ failures

# === Smart Delisted Token Cleanup ===
enable_smart_delisted_cleanup: true     # Auto-clean delisted tokens every 1 loop
delisted_cleanup_interval: 1            # Clean every N loops (1 = every 1 hour)

# === Multi-Chain Settings ===
enable_multi_chain: true
supported_chains:
  - "ethereum"     # Ethereum trading enabled (MetaMask)
  - "solana"       # Solana trading enabled (Phantom)
  # - "base"       # Disabled - need ETH on Base network
  # - "pulsechain" # Disabled - need PLS in wallet
  # - "polygon"    # Disabled - need Polygon wallet
  # - "bsc"        # Disabled - need BSC wallet
  # - "arbitrum"   # Disabled - need Arbitrum wallet
  # - "optimism"   # Disabled - need Optimism wallet

# === Trusted Tokens (skip safety/sentiment checks) ===
trusted_tokens:
  # - "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"  # WETH - temporarily disabled

# === Modes ===
test_mode: false                  # true = simulate only (no chain tx)